Matt hayter/feat/initial simulation visualisation setup
Matt-Hayter/Biological-Models-WebApp pull request #5
Opened 2023-02-04 23:34 UTC by Matt-Hayter

First steps in creating visualisation. Bar chart visuals are as desired, and simulation runs for predator-prey. Need to configure params and time steps to get it working smoothly.

2023-02-07 18:10 UTC, TJ-io requested changes
Couple changes but looking good!

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +        while True:
While True not good coding practice convert to `while trough_counter < self.max_troughs:`

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +        while True:
```suggestion
        while t < self.t_max_stop
```

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +        while True:
```suggestion
        while trough_counter < self.max_troughs:
```

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +                return
```suggestion
```

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +                return
```suggestion
```

2023-02-07 18:10 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +                break
Are you sure you want break here and not return?

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/components/Common/RacerBarChart.vue
> +      for(let i = 0; i < value.length; i++) {
```suggestion
    initialConditions: function(dataPoints) { //Update initial bar lengths upon user param change
      for(let i = 0; i < dataPoints.length; i++) {
```

Use a descriptive name

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/components/Common/RacerBarChart.vue
> +    simRunning: function(value) {
Use a descriptive name not value

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/components/Common/RacerBarChart.vue
> +          this.racerChart.update();
```suggestion
          for (let i = 0; i < this.simData.length; i++) {
              this.chartConfig.data.datasets[0].data[i] = this.simData[i][step]
          }
          this.racerChart.update();
```

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/components/ConfigBar/components/PresetButtons.vue
> +      return this.userPresets.length == 0 && this.$store.state.activeUser.isActive
```suggestion
      return !this.userPresets.length && this.$store.state.activeUser.isActive
```

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/components/ConfigBar/components/PresetButtons.vue
> +      return this.userPresets.length == 0 && !this.$store.state.activeUser.isActive
```suggestion
      return !this.userPresets.length && !this.$store.state.activeUser.isActive
```

2023-02-07 18:10 UTC, TJ-io commented on frontend/frontend/src/views/PredatorPrey/PredPreyChartConfig.js
> +let chartData = {
```suggestion
const CHART_DATA= {
```

if the value doesn't change and is a constant

2023-02-07 18:13 UTC, TJ-io commented on backend/biological_models_app/pred_prey/simulation.py
> +        while True:
Try do while - [see examples here](https://www.freecodecamp.org/news/python-do-while-loop-example/)

2023-02-08 16:19 UTC, Matt-Hayter commented on backend/biological_models_app/pred_prey/simulation.py
> +        while True:
Indefinite loop is prevented using 
if t >= self.t_max_stop: return
so I'll leave this one as discussed.

2023-02-08 16:22 UTC, Matt-Hayter commented on backend/biological_models_app/pred_prey/simulation.py
> +                break
Yeah, means the following while loop will be performed sequentially

2023-02-08 16:40 UTC, Matt-Hayter commented on frontend/frontend/src/views/PredatorPrey/PredPreyChartConfig.js
> +let chartData = {
This one does actually have keys that change, from within RacerBarChart.vue

2023-02-08 16:57 UTC, TJ-io approved these changes

2023-02-08 16:57 UTC, merged